# Generated by Django 4.2.8 on 2023-12-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
