# Generated by Django 4.2.8 on 2023-12-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Post_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
